export const userConstants = {
    GET_USERS_IN_GROUP_REQUEST: "GET_USERS_IN_GROUP_REQUEST",
    GET_USERS_IN_GROUP_SUCCESS: "GET_USERS_IN_GROUP_SUCCESS",
    GET_USERS_IN_GROUP_FAILURE: "GET_USERS_IN_GROUP_FAILURE",
};