export const itemsConstants = {
    GET_ITEMS_REQUEST: "GET_ITEMS_REQUEST",
    GET_ITEMS_SUCCESS: "GET_ITEMS_SUCCESS",
    GET_ITEMS_FAILURE: "GET_ITEMS_FAILURE",

    ADD_ITEM_REQUEST: "ADD_ITEM_REQUEST",
    ADD_ITEM_SUCCESS: "ADD_ITEM_SUCCESS",
    ADD_ITEM_FAILURE: "ADD_ITEM_FAILURE",

    DELETE_ITEM_REQUEST: "DELETE_ITEM_REQUEST",
    DELETE_ITEM_SUCCESS: "DELETE_ITEM_SUCCESS",
    DELETE_ITEM_FAILURE: "DELETE_ITEM_FAILURE",
};